import { Exterior, Interior, Property } from "../types/mock/listing-types";

const interiorData: Interior = {
  appliances: "Water Heater, Range, Dishwasher, Refrigerator",
  basement: "Full, Finished, Walk-Out Access",
  bathroomsTotalDecimal: 4.5,
  buildingAreaUnits: "Square Feet",
  cooling: 1,
  coolingType: "Central Air",
  coolingZones: 3,
  fireplace: 1,
  fireplaceFeatures: "Family Room, Living Room",
  fireplacesTotal: 1,
  flooring: "Hardwood, Vinyl / VCT, Flooring - Vinyl",
  heatZones: 3,
  heating: 1,
  heatingType: "Forced Air",
  interiorFeatures: "Tray Ceiling(s)",
  laundryDimensions: "5X8",
  laundryFeatures: "Second Floor",
  livingArea: 4334,
  roomBedroom3Level: "Second",
  roomBedroom3Width: 13,
  roomBedroom4Area: 156,
  roomBedroom4Features: "Closet, Flooring - Hardwood",
  roomBedroom4Length: 12,
  roomBedroom4Level: "Second",
  roomBedroom4Width: 13,
  roomBedroom5Area: 182,
  roomBedroom5Features: "Closet, Flooring - Vinyl",
  roomBedroom5Length: 14,
  roomBedroom5Level: "Basement",
  roomBedroom5Width: 13,
  roomDiningRoomArea: 323,
  roomDiningRoomFeatures: "Flooring - Hardwood, Window(s) - Picture",
  roomDiningRoomLength: 17,
  roomDiningRoomLevel: "First",
  roomDiningRoomWidth: 19,
  roomFamilyRoomArea: 468,
  roomFamilyRoomFeatures: "Wet Bar",
  roomFamilyRoomLength: 26,
  roomFamilyRoomLevel: "Basement",
  roomFamilyRoomWidth: 18,
  roomKitchenArea: 299,
  roomKitchenFeatures:
    "Closet/Cabinets - Custom Built, Countertops - Stone/Granite/Solid, Kitchen Island",
  roomKitchenLength: 23,
  roomKitchenLevel: "First",
  roomKitchenWidth: 13,
  roomLivingRoomArea: 432,
  roomLivingRoomFeatures: "Flooring - Hardwood, Slider",
  roomLivingRoomLength: 24,
  roomLivingRoomLevel: "First",
  roomLivingRoomWidth: 18,
  roomMasterBathroomFeatures: "Yes",
  roomMasterBedroomArea: 272,
  roomMasterBedroomFeatures: "Walk-In Closet(s), Flooring - Hardwood",
  roomMasterBedroomLength: 16,
  roomMasterBedroomLevel: "Second",
  roomMasterBedroomWidth: 17,
  roomsTotal: 11,
};

const exteriorData: Exterior = {
  architecturalStyle: "Contemporary",
  attachedGarage: 1,
  constructionMaterials: "Frame",
  coveredSpaces: 2,
  exteriorFeatures: ["Porch - Screened", "Patio"],
  farmLandAreaUnits: "Square Feet",
  foundationDetails: "Concrete Perimeter",
  garage: 1,
  garageSpaces: 2,
  lotFeatures: ["Wooded"],
  lotSizeArea: 1.87,
  lotSizeSquareFeet: 81457,
  lotSizeUnits: "Acres",
  parkingFeatures: ["Attached", "Off Street"],
  parkingTotal: 4,
  patioAndPorchFeatures: ["Screened", "Patio"],
  roadFrontageType: "Public",
  roof: ["Rubber", "Metal"],
  sewer: "Private Sewer",
  utilities: ["for Gas Range"],
  waterSource: "Public",
  windowFeatures: ["Insulated Windows"],
};

const mockBrowseDreamHomesData: Property[] = [
  {
    id: "1",
    img: "/images/mock/mock-1.jpg",
    images: [],
    propertyType: "Single Family Home",
    housePrice: "$850,000",
    address: "123 Dream St",
    builtYear: 2015,
    sqft: 2500,
    bedrooms: 4,
    bathrooms: 3,
    city: "Los Angeles",
    description: `"HANDYMAN SPECIAL" Convenient central location close to I93, schools, shopping, medical facilities, restaurants, and churches. Condo amenities include an in-ground pool, tennis courts, playground and two parking spaces. This is the opportunity you have been waiting for. Bring your vision and tools to build equity and make this condo a "HOME".Total rehab needed including, kitchen, full bath, doors, flooring and electrical work. The unit has newer vinyl windows, newer electric SS range, SS refrigerator and new hot water heater as of May 2024. Price reflexes the estimate to rehab this unit.`,
    latitude: 34.0522, // Los Angeles latitude
    longitude: -118.2437, // Los Angeles longitude
    propertySubType: "Single Family Residence",
  },
  {
    id: "2",
    images: [
      "/images/mock/listing-1/listing-1.jpeg",
      "/images/mock/listing-1/listing-2.jpeg",
      "/images/mock/listing-1/listing-3.jpeg",
      "/images/mock/listing-1/listing-4.jpeg",
      "/images/mock/listing-1/listing-5.jpeg",
    ], 
    img: "/images/mock/listing-1/listing-1.jpeg",
    propertyType: "Condo",
    housePrice: "$399,900",
    address: "115 Sandstone Cir #115",
    builtYear: 1984,
    sqft: 1694, 
    bedrooms: 3,
    bathrooms: 3,
    city: "Londonderry",
    fullBaths: 2,
    partialBaths: 1,
    acres: 1.87,
    county: "Middlesex",
    propertySubType: "Single Family Residence",
    halfBaths: 1,
    state: "NH",
    zipCode: "03053",
    latitude: 42.8654,
    longitude: -71.3739,
    description: `"HANDYMAN SPECIAL" Convenient central location close to I93, schools, shopping, medical facilities, restaurants, and churches. Condo amenities include an in-ground pool, tennis courts, playground, and two parking spaces. This is the opportunity you have been waiting for. Bring your vision and tools to build equity and make this condo a "HOME". Total rehab needed including, kitchen, full bath, doors, flooring, and electrical work. The unit has newer vinyl windows, newer electric SS range, SS refrigerator, and new hot water heater as of May 2024. Price reflects the estimate to rehab this unit.`,
    hoaFees: "$550 / month",
    parkingSpaces: 2,
    communityAmenities: ["In-ground pool", "Tennis courts", "Playground"],
    heating: "Forced air",
    cooling: "Central air",
    lotSize: "N/A",
    garage: "None",
    daysOnMarket: 120,
    schoolDistrict: "Londonderry School District",
    location: {
      buildingAreaSource: "Public Records",
      ownerCountry: "USA",
      currency: 'USD',
      directions:
        "From Concord Center: Lowell Rd to Barrett's Mill Rd to Strawberry Hill Rd to Annursnac Hill Rd",
      elementarySchool: "Thoreau",
      highSchool: "Cchs",
      middleOrJuniorSchool: "Cms",
      waterfront: "No",
      zoning: "RES",
    },
    additional: {
      color: "Black",
      leadPaint: "Unknown",
      listingAlert: "No",
      mlsStatus: "New",
      offlineListNumber: 3819155,
      page: 172,
      sqftIncludesBasement: "Yes",
      yearBuiltDetails: "Actual",
      yearBuiltSource: "Builder",
    },
    financial: {
      disclosure: "N",
      downPaymentResource: "No",
      listPricePerSqFt: 553.3,
      pricePerSqFt: 553.3,
      subAgencyOffered: "No",
      taxAnnualAmount: 9999,
      taxAssessedValue: 99999,
      taxBookNumber: "01604",
      taxYear: 2024,
    },
    interior: interiorData,
    exterior: exteriorData,
    nearbyAttractions: [
      "Close to I93",
      "Nearby shopping",
      "Nearby restaurants",
      "Nearby medical facilities",
    ],
    utilities: ["Public water", "Public sewer"],
    appliances: [
      "Newer electric SS range",
      "SS refrigerator",
      "New hot water heater (May 2024)",
    ],
    rehabNeeded: true,
    condition: "Total rehab needed",
    taxes: "$4,740/year",
    flooring: ["Hardwood", "Vinyl"],
    roof: "Shingle",
    exteriorFeatures: ["Vinyl siding"],
    interiorFeatures: ["Dining area", "Primary suite", "Sunroom"],
    basement: "Unfinished",
    laundry: "In unit",
    petPolicy: "Pets allowed",
    financingOptions: ["Conventional loan", "Cash", "Rehab loan"],
    mlsNumber: "73304434",
    status: "Active",
    listingAgent: {
      name: "Eileen Jonah",
      phone: "(603) 548-8685",
      email: "eileen@c21.com",
      office: "Century 21 North East",
    },
    virtualTourLink: "https://example.com/virtual-tour",
    openHouse: {
      date: "October 25, 2024",
      time: "12:00 PM - 3:00 PM",
    },
    externalSection: {
      exteriorColor: "Unknown",
      roofMaterial: "Asphalt shingles",
      foundation: "Concrete",
      exteriorStructure: "Vinyl siding",
      roadType: "Public",
      roadSurface: "Paved",
    },
    additionalSection: {
      levels: "2",
      squareFootageFinishedAboveGrade: 1694,
      basement: "Full, unfinished",
      waterSource: "Public",
      sewer: "Public",
      heatingSystem: "Forced Air",
      coolingSystem: "Central Air",
      electric: "Circuit Breakers",
      hotWater: "Electric",
      waterHeaterAge: "May 2024",
      appliancesIncluded: ["Range - Electric", "Refrigerator"],
      parking: {
        parkingSpaces: 2,
        parkingType: "Off-Street, Assigned",
      },
    },
  },

  {
    id: "3",
    images: [],
    img: "/images/mock/mock-3.jpg",
    propertyType: "Townhouse",
    housePrice: "$720,000",
    address: "789 Suburb Rd",
    builtYear: 2018,
    sqft: 2000,
    bedrooms: 3,
    bathrooms: 2,
    city: "San Francisco",
    description: "Spacious Townhouse Near Golden Gate",
    latitude: 37.7749, // San Francisco latitude
    longitude: -122.4194, // San Francisco longitude
    propertySubType: "Single Family Residence",
  },
  {
    id: "4",
    images: [],
    img: "/images/mock/mock-4.jpg",
    propertyType: "Restaurant",
    housePrice: "$1,200,000",
    address: "321 Foodie Lane",
    builtYear: 2010,
    sqft: 3000,
    bedrooms: 0,
    bathrooms: 2,
    city: "Austin",
    description: "Restaurant in the Heart of Austin, TX, 78687",
    latitude: 30.2672, // Austin latitude
    longitude: -97.7431, // Austin longitude
    propertySubType: "Single Family Residence",
  },
  {
    id: "5",
    images: [],
    img: "/images/mock/mock-5.jpg",
    propertyType: "Luxury Villa",
    housePrice: "$3,500,000",
    address: "888 Elite Blvd",
    builtYear: 2021,
    sqft: 4000,
    bedrooms: 5,
    bathrooms: 5,
    city: "Beverly Hills",
    description: "Luxurious Villa with Stunning Views",
    latitude: 34.0736, // Beverly Hills latitude
    longitude: -118.4004, // Beverly Hills longitude
    propertySubType: "Single Family Residence",
  },
];

export default mockBrowseDreamHomesData;
