export const MA_COUNTIES: Record<string, string[]> = {
  Barnstable: [
    'Barnstable',
    'Bourne',
    'Brewster',
    'Chatham',
    'Dennis',
    'Eastham',
    'Falmouth',
    'Harwich',
    'Mashpee',
    'Orleans',
    'Provincetown',
    'Sandwich',
    'Truro',
    'Wellfleet',
    'Yarmouth'
  ],
  Berkshire: [
    'Adams',
    'Alford',
    'Becket',
    'Cheshire',
    'Clarksburg',
    'Dalton',
    'Egremont',
    'Florida',
    'Great Barrington',
    'Hancock',
    'Hinsdale',
    'Lanesborough',
    'Lee',
    'Lenox',
    'Monterey',
    'Mount Washington',
    'New Ashford',
    'New Marlborough',
    'North Adams',
    'Otis',
    'Peru',
    'Pittsfield',
    'Richmond',
    'Sandisfield',
    'Savoy',
    'Sheffield',
    'Stockbridge',
    'Tyringham',
    'Washington',
    'West Stockbridge',
    'Williamstown',
    'Windsor'
  ],
  Bristol: [
    'Acushnet',
    'Attleboro',
    'Berkley',
    'Dartmouth',
    'Dighton',
    'Easton',
    'Fairhaven',
    'Fall River',
    'Freetown',
    'Mansfield',
    'New Bedford',
    'North Attleborough',
    'Norton',
    'Raynham',
    'Rehoboth',
    'Seekonk',
    'Somerset',
    'Swansea',
    'Taunton',
    'Westport'
  ],
  Dukes: ['Aquinnah', 'Chilmark', 'Edgartown', 'Gosnold', 'Oak Bluffs', 'Tisbury', 'West Tisbury'],
  Essex: [
    'Amesbury',
    'Andover',
    'Beverly',
    'Boxford',
    'Danvers',
    'Essex',
    'Georgetown',
    'Gloucester',
    'Groveland',
    'Hamilton',
    'Haverhill',
    'Ipswich',
    'Lawrence',
    'Lynn',
    'Lynnfield',
    'Manchester',
    'Marblehead',
    'Merrimac',
    'Methuen',
    'Middleton',
    'Nahant',
    'Newbury',
    'Newburyport',
    'North Andover',
    'Peabody',
    'Rockport',
    'Rowley',
    'Salem',
    'Salisbury',
    'Saugus',
    'Swampscott',
    'Topsfield',
    'Wenham',
    'West Newbury'
  ],
  Franklin: [
    'Ashfield',
    'Bernardston',
    'Buckland',
    'Charlemont',
    'Colrain',
    'Conway',
    'Deerfield',
    'Erving',
    'Gill',
    'Greenfield',
    'Hawley',
    'Heath',
    'Leverett',
    'Leyden',
    'Monroe',
    'Montague',
    'New Salem',
    'Northfield',
    'Orange',
    'Rowe',
    'Shelburne',
    'Shutesbury',
    'Sunderland',
    'Warwick',
    'Wendell',
    'Whately'
  ],
  Hampden: [
    'Agawam',
    'Blandford',
    'Brimfield',
    'Chester',
    'Chicopee',
    'East Longmeadow',
    'Granville',
    'Hampden',
    'Holland',
    'Holyoke',
    'Longmeadow',
    'Ludlow',
    'Monson',
    'Montgomery',
    'Palmer',
    'Russell',
    'Southwick',
    'Springfield',
    'Tolland',
    'Wales',
    'Westfield',
    'West Springfield',
    'Wilbraham'
  ],
  Hampshire: [
    'Amherst',
    'Belchertown',
    'Chesterfield',
    'Cummington',
    'Easthampton',
    'Goshen',
    'Granby',
    'Hadley',
    'Hatfield',
    'Huntington',
    'Middlefield',
    'Northampton',
    'Pelham',
    'Plainfield',
    'South Hadley',
    'Southampton',
    'Ware',
    'Westhampton',
    'Williamsburg',
    'Worthington'
  ],
  Middlesex: [
    'Acton',
    'Arlington',
    'Ashby',
    'Ashland',
    'Ayer',
    'Bedford',
    'Belmont',
    'Billerica',
    'Boxborough',
    'Burlington',
    'Cambridge',
    'Carlisle',
    'Chelmsford',
    'Concord',
    'Dracut'
  ]
}
